controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\SecurityController::login

top_visitors:
    path: /top-visitors
    controller: App\Controller\FicheFraisController::topVisitors